version: '3.8'

services:
  web:
    depends_on: [ db ]
    build:
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "${DATABASE_URL}" # URL DB
      GMAIL_APP_PASSWORD: "${GMAIL_APP_PASSWORD}"
      WAIT_HOSTS: db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go -b 0.0.0.0

  db:
    image: mysql
    restart: always
    container_name: bdGolang
    environment:
      MYSQL_DATABASE: api-golang
      MYSQL_USER: maka
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - mysqldb-data:/var/lib/mysql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  phpmyadmin:
    depends_on: [ db ]
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80

volumes:
  mysqldb-data:
